# Dockerfile.scratch (Minimales Image)
FROM golang:1.25.5-alpine AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -ldflags="-w -s" -o gitlab-downloader ./cmd/gitlab-downloader

FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /build/gitlab-downloader /gitlab-downloader

ENV GITLAB_URL="https://gitlab.com"

ENTRYPOINT ["/gitlab-downloader"]
