build_project:
  image: docker.io/golang:alpine
  tags: [docker]
  stage: build
  before_script:
    - apk update --no-cache
    - apk add --no-cache make zip golangci-lint
    - go mod tidy
  script:
    - make release
  artifacts:
    paths:
      - bin/releases/markscribe-*.tar.gz
      - bin/releases/markscribe-*.zip
    expire_in: 1 hour
  except:
    - main

variables:
  GITLAB_IMAGE: $CI_REGISTRY_IMAGE

build_gitlab_dev:
  variables:
    GITLAB_IMAGE: $CI_REGISTRY_IMAGE
  stage: build
  image: quay.io/podman/stable:latest
  tags: [docker]

  before_script:
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ls -la /proc/sys/fs/binfmt_misc/ | grep qemu || echo "QEMU registered"
    #- podman run --rm --privileged docker.io/tonistiigi/binfmt:latest --install all

  script:
    - |
      echo "🔨 Building multi-arch images"
      
      # Manifest erstellen
      podman manifest create $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA

      # AMD64 Build
      echo "📦 Building AMD64..."
      podman build \
        --platform linux/amd64 \
        --manifest $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA \
        -f Dockerfile .

      # ARM64 Build - WICHTIG: --platform linux/arm64!
      echo "📦 Building ARM64..."
      podman build \
        --platform linux/arm64 \
        --manifest $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA \
        -f Dockerfile .
      
      # Manifest inspizieren
        echo "📊 Manifest enthält:"
        podman manifest inspect $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA | grep -A 3 "platform"

      # Manifest pushen (mit --all für alle Architekturen!)
        echo "📤 Pushing manifest..."
        podman manifest push --all $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA

      # Latest tag (auch als Manifest!)
        echo "🏷️  Creating latest tag..."
        podman manifest create $GITLAB_IMAGE:latest
        podman manifest add $GITLAB_IMAGE:latest $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA
        podman manifest push --all $GITLAB_IMAGE:latest
        
        echo "✅ Build complete!"
  except:
    - main
