build_project:
  image: docker.io/golang:alpine
  tags: [docker]
  stage: build
  before_script:
    - apk update --no-cache
    - apk add --no-cache make zip golangci-lint
    - go mod tidy
  script:
    - make release
  artifacts:
    paths:
      - bin/releases/markscribe-*.tar.gz
      - bin/releases/markscribe-*.zip
    expire_in: 1 hour
  except:
    - main

variables:
  GITLAB_IMAGE: $CI_REGISTRY_IMAGE

build_gitlab_dev:
  variables:
    GITLAB_IMAGE: $CI_REGISTRY_IMAGE
  stage: build
  image: quay.io/podman/stable:latest
  tags: [docker]

  before_script:
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ls -la /proc/sys/fs/binfmt_misc/ | grep qemu || echo "QEMU registered"
    #- podman run --rm --privileged docker.io/tonistiigi/binfmt:latest --install all

  script:
    - |
      echo "🔨 Building multi-arch images"
      
      # Manifest erstellen
      podman manifest create $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA

      # AMD64 Build
      echo "📦 Building AMD64..."
       set -e  # Exit on error
      
      echo "🔨 Building multi-arch images"
      
      # Manifest erstellen
      podman manifest create $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA || {
        echo "❌ Failed to create manifest"
        exit 1
      }

      # AMD64 Build mit Error Handling
      echo ""
      echo "📦 Building AMD64..."
      podman build \
        --replace \
        --platform linux/amd64 \
        --manifest $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA \
        --file Dockerfile \
        . || {
        echo "❌ AMD64 build failed!"
        exit 1
      }
      
      echo "✅ AMD64 build successful"

      # ARM64 Build mit Error Handling
      echo ""
      echo "📦 Building ARM64 (this may take longer)..."
      podman build \
        --replace \
        --platform linux/arm64 \
        --manifest $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA \
        --file Dockerfile \
        . || {
        echo "❌ ARM64 build failed!"
        podman manifest rm $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA 2>/dev/null || true
        exit 1
      }
      
      echo "✅ ARM64 build successful"

      # Manifest inspizieren BEVOR wir pushen
      echo ""
      echo "📊 Manifest contains:"
      podman manifest inspect $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA | \
        grep -A 2 "platform" | grep -E "architecture|os" || {
        echo "❌ Manifest inspection failed!"
        exit 1
      }
      
      # Prüfen ob beide Architekturen vorhanden sind
      ARCH_COUNT=$(podman manifest inspect $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA | \
        grep -c "architecture" || echo "0")
      
      if [ "$ARCH_COUNT" -lt 2 ]; then
        echo "❌ Expected 2 architectures, found $ARCH_COUNT"
        podman manifest inspect $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA
        exit 1
      fi
      
      echo "✅ Found $ARCH_COUNT architectures in manifest"

      # Jetzt pushen
      echo ""
      echo "📤 Pushing manifest with all images..."
      podman manifest push --all $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA || {
        echo "❌ Push failed!"
        exit 1
      }

      # Latest tag
      echo ""
      echo "🏷️  Creating latest tag..."
      podman manifest create $GITLAB_IMAGE:latest
      podman manifest add $GITLAB_IMAGE:latest $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA
      podman manifest push --all $GITLAB_IMAGE:latest

      echo ""
      echo "✅ Build and push completed!"
      echo "Verify with:"
      echo "  podman manifest inspect $GITLAB_IMAGE:latest"
  except:
    - main
