build_project:
  image: docker.io/golang:alpine
  tags: [docker]
  stage: build
  before_script:
    - apk update --no-cache
    - apk add --no-cache make zip golangci-lint
    - go mod tidy
  script:
    - make release
  artifacts:
    paths:
      - bin/releases/markscribe-*.tar.gz
      - bin/releases/markscribe-*.zip
    expire_in: 1 hour
  except:
    - main

variables:
  GITLAB_IMAGE: $CI_REGISTRY_IMAGE

build_gitlab_dev:
  variables:
    GITLAB_IMAGE: $CI_REGISTRY_IMAGE
  stage: build
  image: quay.io/podman/stable:latest
  tags: [docker]

  before_script:
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ls -la /proc/sys/fs/binfmt_misc/ | grep qemu || echo "QEMU registered"
    #- podman run --rm --privileged docker.io/tonistiigi/binfmt:latest --install all

  script:
    - |
      set -e  # Exit on error
      
      echo "🔨 Building multi-arch images"
      
      # VOLLSTÄNDIGES Cleanup: Manifests UND Images
      echo "🧹 Cleaning up old builds..."
      podman manifest rm $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA 2>/dev/null || true
      podman manifest rm $GITLAB_IMAGE:latest 2>/dev/null || true
      podman rmi $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA 2>/dev/null || true
      podman rmi $GITLAB_IMAGE:latest 2>/dev/null || true
      
      # Sicherstellen dass nichts mehr da ist
      echo "📋 Checking local state..."
      podman images | grep "$CI_COMMIT_SHORT_SHA" || echo "✅ Clean slate"
      
      # Manifest erstellen
      echo "📋 Creating new manifest..."
      podman manifest create $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA

      # AMD64 Build
      echo ""
      echo "📦 Building AMD64..."
      podman build \
      --platform linux/amd64 \
      --manifest $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA \
      --file Dockerfile \
      .
      
      echo "✅ AMD64 build successful"

      # ARM64 Build
      echo ""
      echo "📦 Building ARM64 (this may take longer)..."
      podman build \
      --platform linux/arm64 \
      --manifest $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA \
      --file Dockerfile \
      .
      
      echo "✅ ARM64 build successful"

      # Push manifest
      echo ""
      echo "📤 Pushing manifest with all images..."
      podman manifest push --all $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA

      # Latest tag
      echo ""
      echo "🏷️  Creating latest tag..."
      podman manifest create $GITLAB_IMAGE:latest
      podman manifest add $GITLAB_IMAGE:latest $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA
      podman manifest push --all $GITLAB_IMAGE:latest

      echo ""
      echo "✅ Build and push completed!"
      echo ""
      echo "📦 Available images:"
      echo "   • $GITLAB_IMAGE:$CI_COMMIT_SHORT_SHA"
      echo "   • $GITLAB_IMAGE:latest"
      echo ""
      echo "🧪 Test with:"
      echo "   podman pull --platform linux/amd64 $GITLAB_IMAGE:latest"
      echo "   podman pull --platform linux/arm64 $GITLAB_IMAGE:latest"
  except:
    - main
